rescue_path: "file:////home/cdsw/ons-spark/ons-spark/data/animal_rescue.parquet"
rescue_clean_path: "file:////home/cdsw/ons-spark/data/rescue_clean.parquet"
rescue_path_orc: "file:////home/cdsw/ons-spark/ons-spark/data/animal_rescue.orc"
rescue_path_avro: "file:////home/cdsw/ons-spark/ons-spark/data/animal_rescue.avro"
rescue_path_csv: "file:////home/cdsw/ons-spark/ons-spark/data/animal_rescue.csv"
temp_outputs: "file:////home/cdsw/ons-spark/ons-spark/data/temp_outputs/"
population_path: "file:////home/cdsw/ons-spark/ons-spark/data/population.parquet"
checkpoint_path: "file:////home/cdsw/ons-spark/checkpoints"
rescue_with_pop_path_csv: "file:////home/cdsw/ons-spark/ons-spark/data/rescue_with_pop.csv"
rescue_with_pop_path_parquet: "file:////home/cdsw/ons-spark/ons-spark/data/rescue_with_pop.parquet"
staging_table_example: "staging_example_"
database: "train_tmp"
