rescue_path: "file:////home/cdsw/ons-spark/ons-spark/data/animal_rescue.parquet"
rescue_path_csv: "file:////home/cdsw/ons-spark/ons-spark/data/animal_rescue.csv"
population_path: "file:////home/cdsw/ons-spark/ons-spark/data/population.parquet"
checkpoint_path: "file:////home/cdsw/ons-spark/checkpoints"
