#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Spark at the ONS  # The title of the book. Will be placed in the left navbar.
author                      : Wil Roberts & Adrian Prince  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/best-practice-and-impact/ons-spark  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: binder_tests  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-95MGHSRD0S
  #home_page_in_navbar: false

# Our own added configs
execute:
  execute_notebooks: 'off'

sphinx:
  extra_extensions:
    - sphinx_tabs.tabs
    - sphinx.ext.todo
  config:
    todo_include_todos: true
    language: en
    html_show_copyright: false


launch_buttons:
  binderhub_url : "https://mybinder.org/v2/gh/best-practice-and-impact/ons-spark/binder_tests"